apiVersion: apps/v1
kind: Deployment
metadata:
  name: goconsumer
  labels:
    app: goconsumer
spec:
  replicas: 3
  selector:
    matchLabels:
      app: goconsumer
  template:
    metadata:
      labels:
        app: goconsumer
    spec:
      containers:
      - name: goconsumer
        image: rodolfohok/gointensivo:latest
        ports:
        - containerPort: 8080